screen.loading=ffffff
screen.loading.bar=ffffff
screen.loading.outline=FFFFFF
screen.loading.progress=FFFFFF
screen.loading.blend=off
collar.white=e6e6e6
collar.orange=eb7f36
collar.magenta=be49c9
collar.light_blue=6286d1
collar.yellow=c3b61d
collar.lime=3bbd31
collar.pink=d98199
collar.gray=424242
collar.light_gray=a0a7a7
collar.cyan=267191
collar.purple=7e34bf
collar.blue=232f91
collar.brown=56331c
collar.green=364b18
collar.red=9e2b27
collar.black=080a0f
dye.white=e6e6e6
dye.orange=eb7f36
dye.magenta=be49c9
dye.lightBlue=6286d1
dye.yellow=c3b61d
dye.lime=3bbd31
dye.pink=d98199
dye.gray=424242
dye.silver=a0a7a7
dye.cyan=267191
dye.purple=7e34bf
dye.blue=232f91
dye.brown=56331c
dye.green=364b18
dye.red=9e2b27
dye.black=080a0f
fog.nether=1d0404
potion.absorption=2552a5
potion.bad_omen=b6138
potion.blindness=1f1f23
potion.conduit_power=1dc2d1
potion.dolphins_grace=88a3be
potion.fire_resistance=e49a3a
potion.glowing=94a061
potion.haste=d9c043
potion.health_boost=f87d23
potion.hero_of_the_village=44ff44
potion.hunger=587653
potion.instant_damage=430a09
potion.instant_health=f82423
potion.invisibility=7f8392
potion.jump_boost=22ff4c
potion.levitation=ceffff
potion.luck=339900
potion.mining_fatigue=4a4217
potion.nausea=551d4a
potion.night_vision=1f1fa1
potion.poison=4e9331
potion.regeneration=cd5cab
potion.resistance=99453a
potion.saturation=f82423
potion.slow_falling=ffefd1
potion.slowness=5a6c81
potion.speed=7cafc6
potion.strength=932423
potion.unluck=c0a44d
potion.water_breathing=2e5299
potion.weakness=484d48
potion.wither=352a27
# potion.water represents a plain bottle of water
potion.water=385dc6
sheep.white=e6e6e6
sheep.orange=eb7f36
sheep.magenta=be49c9
sheep.light_blue=6286d1
sheep.yellow=c3b61d
sheep.lime=3bbd31
sheep.pink=d98199
sheep.gray=424242
sheep.light_gray=a0a7a7
sheep.cyan=267191
sheep.purple=7e34bf
sheep.blue=232f91
sheep.brown=56331c
sheep.green=364b18
sheep.red=9e2b27
sheep.black=080a0f